version: 2

jobs:
  build:
    working_directory: /home/reaction

    docker:
      - image: node:8

    environment:
      - DOCKER_VERSION: 17.05.0-ce
      - DOCKER_COMPOSE_VERSION: 1.15.0
      - METEOR_ALLOW_SUPERUSER: true
      - TOOL_NODE_FLAGS: "--max-old-space-size=4096"

    steps:
      - setup_remote_docker
      - checkout

      # install OS dependencies
      - restore_cache:
          name: Restoring Meteor cache
          key: meteor

      - run: .circleci/install.sh

      - save_cache:
          name: Saving Meteor to cache
          key: meteor
          paths:
            - ~/.meteor

      # install app dependencies

      - run: meteor npm install

      # run tests
      - restore_cache:
          name: Restoring Meteor dev_bundle cache
          key: dev_bundle

      # run reaction tests
      - run: .circleci/tests.sh

      - save_cache:
          name: Saving Meteor dev_bundle to cache
          key: dev_bundle
          paths:
            - /home/reaction/.meteor/local

      - run:
          command: .circleci/build.sh
          no_output_timeout: 30m

      - run:
          command: .reaction/jsdoc/build.sh
          no_output_timeout: 2m

      # deploy the build (if on a deployment branch)

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [[ "${API_DOC_BUCKET}" && "${API_DOC_BUCKET_REGION}" ]]; then
                aws s3 sync /tmp/reaction-docs ${API_DOC_BUCKET} --delete --region ${API_DOC_BUCKET_REGION}
              else
                echo "S3 bucket configuration not found for jsdocs"
                echo "Set API_DOC_BUCKET and API_DOC_BUCKET_REGION to build and deploy jsdocs to S3"
              fi
            else
              echo "Not master branch so not deploying"
            fi
      - deploy:
          name: Docker Image Deploment
          command: .circleci/deploy.sh
