environment:
  name: staging
  service:
    name: reaction2-core
    cluster: core
    certificate_arn: arn:aws:acm:us-west-2:773713188930:certificate/c2979a7a-7b84-43ed-b3a7-24b0256a1b9f
    root_domain: staging.reactioncommerce.com
    dns_name: reaction2-core
    desired_task_count: 2
    min_task_count: 0
    max_task_count: 0
    min_healthy_percent: 100
    max_percent: 200
    alb_listener_port: 80
    alb_listener_path: /
    alb_listener_rule_priority: 1
    alb_health_check_path: /health
    task-definition:
      name: core2
      cpu: 500
      memory: 1800
      container:
        name: core2
        port: 3000
        image: reactioncommerce/reaction
        image_tag: latest
        env_params:
        - name: REACTION_AUTH
        - name: REACTION_EMAIL
        - name: REACTION_USER
        - name: MONGO_URL
        - name: ROOT_URL
        - name: SKIP_FIXTURES
